modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GPLv3"
issueTrackerURL="https://discord.gg/MWvCEjSSNe" #optional
[[mods]] #mandatory
modId="singleplayersleepmod" #mandatory
version="1.16.5_1.0.2" #${file.jarVersion}" #mandatory
displayName="Single Player Sleep Mod" #mandatory
updateJSONURL="https://raw.githubusercontent.com/JoelGodOfwar/SinglePlayerSleepMod/main/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/singleplayersleep" #optional
logoFile="spslogo.png" #optional
credits="Xisumavoid, Tangotek, and Zedaph; and diesieben07 for helping me." #optional
authors="JoelGodOfWar" #optional
description='''
This is a Forge port of my SinglePlayerSleep bukkit plugin, based on the VanillaTweaks "Multiplayer Sleep" Datapack
It is not a complete port, as Forge does not have proper permissions, but it does what Multiplayer Sleep does without using scoreboards.
'''


# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
