
#General configuration settings
[settings]
	#Defines the sleep message to be displayed when a player sleeps.
	#%1$s is a placeholder for the sleeping player's name.
	str_singleplayersleep_SleepMessage = "%1$s went to bed. Sweet dreams!"
	#Enable or Disable this mod
	bool_singleplayersleep_Enabled = true
	#Define the length of time to delay in ticks before changing the time.
	#200(10 seconds) is default, as it is just over the vanilla length for single player.
	#Range: > 0
	int_singleplayersleep_SleepLength = 200

